name: Build and Push Docker Image

on:
  push:
    branches:
      - master                # triggers when you push to master
  workflow_dispatch:          # allows manual trigger from GitHub UI

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: List files for debug
      run: ls -R

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install dependencies
      run: npm install
      working-directory: Habit_tracker

    - name: Build project
      run: npm run build
      working-directory: Habit_tracker

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: ./Habit_tracker
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/habit_real:latest
